// ============================================================================
// Compound Database — common compounds with physical properties
// ============================================================================

export interface Compound {
  formula: string;          // Chemical formula
  commonNameEn: string;     // Common name in English
  commonNameAr: string;     // Common name in Arabic
  molarMass: number;        // g/mol
  density?: number;         // g/cm³ (or g/mL for liquids)
  meltingPoint?: number;    // °C
  boilingPoint?: number;    // °C
  stateAtRoomTemp: "solid" | "liquid" | "gas";
  stateAr: string;          // Arabic state name
  category: "household" | "lab" | "food" | "industrial";
  hazardLevel: "low" | "medium" | "high";
  descriptionEn: string;
  descriptionAr: string;
  homeUsesEn?: string[];
  homeUsesAr?: string[];
}

export const COMPOUNDS: Record<string, Compound> = {
  // ---- Household compounds ----
  "H2O": {
    formula: "H2O",
    commonNameEn: "Water",
    commonNameAr: "الماء",
    molarMass: 18.015,
    density: 1.0,
    meltingPoint: 0,
    boilingPoint: 100,
    stateAtRoomTemp: "liquid",
    stateAr: "سائل",
    category: "household",
    hazardLevel: "low",
    descriptionEn: "Universal solvent, essential for all life.",
    descriptionAr: "مذيب عام، أساسي لكل أشكال الحياة.",
    homeUsesEn: ["Drinking", "Cooking", "Cleaning", "Dilution"],
    homeUsesAr: ["شرب", "طبخ", "تنظيف", "تخفيف"],
  },
  "NaCl": {
    formula: "NaCl",
    commonNameEn: "Table Salt",
    commonNameAr: "ملح الطعام",
    molarMass: 58.44,
    density: 2.16,
    meltingPoint: 801,
    boilingPoint: 1413,
    stateAtRoomTemp: "solid",
    stateAr: "صلب",
    category: "household",
    hazardLevel: "low",
    descriptionEn: "Common salt used in cooking and food preservation.",
    descriptionAr: "ملح شائع يستخدم في الطبخ وحفظ الطعام.",
    homeUsesEn: ["Cooking", "Food preservation", "De-icing", "Saline solution"],
    homeUsesAr: ["طبخ", "حفظ الطعام", "إذابة الجليد", "محلول ملحي"],
  },
  "NaHCO3": {
    formula: "NaHCO3",
    commonNameEn: "Baking Soda",
    commonNameAr: "بيكربونات الصوديوم",
    molarMass: 84.01,
    density: 2.20,
    meltingPoint: 50,
    boilingPoint: 333,
    stateAtRoomTemp: "solid",
    stateAr: "صلب",
    category: "household",
    hazardLevel: "low",
    descriptionEn: "Baking soda, used in cooking, cleaning, and as an antacid.",
    descriptionAr: "بيكنج صودا، تستخدم في الطبخ والتنظيف وكمضاد للحموضة.",
    homeUsesEn: ["Baking", "Cleaning", "Antacid", "Deodorizer", "Fire extinguisher"],
    homeUsesAr: ["خبز", "تنظيف", "مضاد حموضة", "إزالة الروائح", "طفاية حريق"],
  },
  "CH3COOH": {
    formula: "CH3COOH",
    commonNameEn: "Vinegar (Acetic Acid)",
    commonNameAr: "الخل (حمض الخليك)",
    molarMass: 60.052,
    density: 1.049,
    meltingPoint: 17,
    boilingPoint: 118,
    stateAtRoomTemp: "liquid",
    stateAr: "سائل",
    category: "household",
    hazardLevel: "low",
    descriptionEn: "Acetic acid diluted in water (typically 4-8%), used in cooking and cleaning.",
    descriptionAr: "حمض الخليك المخفف بالماء (عادة 4-8%)، يستخدم في الطبخ والتنظيف.",
    homeUsesEn: ["Cooking", "Cleaning", "Pickling", "Weed killer", "Descaler"],
    homeUsesAr: ["طبخ", "تنظيف", "تخليل", "مبيد أعشاب", "إزالة الترسبات"],
  },
  "H2O2": {
    formula: "H2O2",
    commonNameEn: "Hydrogen Peroxide",
    commonNameAr: "بيروكسيد الهيدروجين",
    molarMass: 34.014,
    density: 1.45,
    meltingPoint: -0.43,
    boilingPoint: 150,
    stateAtRoomTemp: "liquid",
    stateAr: "سائل",
    category: "household",
    hazardLevel: "medium",
    descriptionEn: "Common 3% solution used as disinfectant and antiseptic.",
    descriptionAr: "محلول 3% شائع يستخدم كمطهر ومعقم.",
    homeUsesEn: ["Disinfectant", "Wound cleaning", "Bleaching", "Cleaning"],
    homeUsesAr: ["مطهر", "تنظيف الجروح", "تبييض", "تنظيف"],
  },
  "C12H22O11": {
    formula: "C12H22O11",
    commonNameEn: "Table Sugar (Sucrose)",
    commonNameAr: "السكر (السكروز)",
    molarMass: 342.3,
    density: 1.587,
    meltingPoint: 186,
    boilingPoint: 0,
    stateAtRoomTemp: "solid",
    stateAr: "صلب",
    category: "food",
    hazardLevel: "low",
    descriptionEn: "Common table sugar used in cooking and baking.",
    descriptionAr: "سكر الطعام الشائع المستخدم في الطبخ والخبز.",
    homeUsesEn: ["Sweetening", "Baking", "Preservation", "Fermentation"],
    homeUsesAr: ["تحلية", "خبز", "حفظ", "تخمر"],
  },
  "C6H12O6": {
    formula: "C6H12O6",
    commonNameEn: "Glucose",
    commonNameAr: "الجلوكوز",
    molarMass: 180.156,
    density: 1.54,
    meltingPoint: 146,
    boilingPoint: 0,
    stateAtRoomTemp: "solid",
    stateAr: "صلب",
    category: "food",
    hazardLevel: "low",
    descriptionEn: "Simple sugar, main energy source for living organisms.",
    descriptionAr: "سكر بسيط، المصدر الرئيسي للطاقة للكائنات الحية.",
    homeUsesEn: ["Energy source", "Baking", "Medical (IV)"],
    homeUsesAr: ["مصدر طاقة", "خبز", "طبي (وريدي)"],
  },
  "NH3": {
    formula: "NH3",
    commonNameEn: "Ammonia",
    commonNameAr: "الأمونيا",
    molarMass: 17.031,
    density: 0.73,
    meltingPoint: -77.7,
    boilingPoint: -33.3,
    stateAtRoomTemp: "gas",
    stateAr: "غاز",
    category: "household",
    hazardLevel: "medium",
    descriptionEn: "Household ammonia solution (5-10%) used in cleaning.",
    descriptionAr: "محلول الأمونيا المنزلي (5-10%) يستخدم في التنظيف.",
    homeUsesEn: ["Cleaning", "Glass cleaner", "Deodorizer"],
    homeUsesAr: ["تنظيف", "منظف زجاج", "إزالة الروائح"],
  },
  "HCl": {
    formula: "HCl",
    commonNameEn: "Hydrochloric Acid (Muriatic Acid)",
    commonNameAr: "حمض الهيدروكلوريك",
    molarMass: 36.458,
    density: 1.18,
    meltingPoint: -114.2,
    boilingPoint: -85.1,
    stateAtRoomTemp: "gas",
    stateAr: "غاز",
    category: "household",
    hazardLevel: "high",
    descriptionEn: "Muriatic acid used for pool maintenance and heavy cleaning. Handle with care.",
    descriptionAr: "حمض المورياتيك المستخدم لصيانة المسابح والتنظيف الثقيل. تعامل بحذر.",
    homeUsesEn: ["Pool maintenance", "Concrete etching", "Descaling"],
    homeUsesAr: ["صيانة المسبح", "نقش الخرسانة", "إزالة الترسبات"],
  },
  "C2H5OH": {
    formula: "C2H5OH",
    commonNameEn: "Ethanol (Alcohol)",
    commonNameAr: "الإيثانول (الكحول)",
    molarMass: 46.069,
    density: 0.789,
    meltingPoint: -114.1,
    boilingPoint: 78.37,
    stateAtRoomTemp: "liquid",
    stateAr: "سائل",
    category: "household",
    hazardLevel: "medium",
    descriptionEn: "Ethyl alcohol (70% for disinfection), used as antiseptic and solvent.",
    descriptionAr: "كحول إيثيلي (70% للتعقيم)، يستخدم كمطهر ومذيب.",
    homeUsesEn: ["Disinfection", "Cleaning", "Solvent", "Hand sanitizer"],
    homeUsesAr: ["تعقيم", "تنظيف", "مذيب", "معقم يدين"],
  },
  "CaCO3": {
    formula: "CaCO3",
    commonNameEn: "Calcium Carbonate (Chalk)",
    commonNameAr: "كربونات الكالسيوم",
    molarMass: 100.09,
    density: 2.71,
    meltingPoint: 825,
    boilingPoint: 0,
    stateAtRoomTemp: "solid",
    stateAr: "صلب",
    category: "household",
    hazardLevel: "low",
    descriptionEn: "Found in chalk, marble, antacids, and calcium supplements.",
    descriptionAr: "يوجد في الطباشير والرخام ومضادات الحموضة ومكملات الكالسيوم.",
    homeUsesEn: ["Antacid", "Calcium supplement", "Chalk"],
    homeUsesAr: ["مضاد حموضة", "مكمل كالسيوم", "طباشير"],
  },
  "CuSO4": {
    formula: "CuSO4",
    commonNameEn: "Copper Sulfate (Blue Vitriol)",
    commonNameAr: "كبريتات النحاس",
    molarMass: 159.609,
    density: 3.60,
    meltingPoint: 650,
    boilingPoint: 0,
    stateAtRoomTemp: "solid",
    stateAr: "صلب",
    category: "household",
    hazardLevel: "medium",
    descriptionEn: "Blue crystals used in home chemistry experiments (crystal growing).",
    descriptionAr: "بلورات زرقاء تستخدم في تجارب الكيمياء المنزلية (زراعة البلورات).",
    homeUsesEn: ["Crystal growing", "Algae control", "Electroplating"],
    homeUsesAr: ["زراعة البلورات", "مكافحة الطحالب", "طلاء كهربائي"],
  },
  "KMnO4": {
    formula: "KMnO4",
    commonNameEn: "Potassium Permanganate",
    commonNameAr: "برمنغنات البوتاسيوم",
    molarMass: 158.034,
    density: 2.70,
    meltingPoint: 240,
    boilingPoint: 0,
    stateAtRoomTemp: "solid",
    stateAr: "صلب",
    category: "household",
    hazardLevel: "medium",
    descriptionEn: "Purple crystals, strong oxidizer, used as disinfectant and in water treatment.",
    descriptionAr: "بلورات بنفسجية، مؤكسد قوي، يستخدم كمطهر ومعالجة المياه.",
    homeUsesEn: ["Water treatment", "Disinfectant", "Fire starter"],
    homeUsesAr: ["معالجة المياه", "مطهر", "مشتعل للنار"],
  },
  "NaOH": {
    formula: "NaOH",
    commonNameEn: "Sodium Hydroxide (Lye)",
    commonNameAr: "هيدروكسيد الصوديوم",
    molarMass: 40.0,
    density: 2.13,
    meltingPoint: 318,
    boilingPoint: 1388,
    stateAtRoomTemp: "solid",
    stateAr: "صلب",
    category: "household",
    hazardLevel: "high",
    descriptionEn: "Lye used in soap making and drain cleaning. Highly corrosive.",
    descriptionAr: "الصودا الكاوية المستخدمة في صناعة الصابون وتنظيف البالوعات. شديدة التآكل.",
    homeUsesEn: ["Soap making", "Drain cleaner", "Oven cleaner"],
    homeUsesAr: ["صناعة الصابون", "منظف بالوعات", "منظف أفران"],
  },
  "C3H8O": {
    formula: "C3H8O",
    commonNameEn: "Isopropyl Alcohol (Rubbing Alcohol)",
    commonNameAr: "كحول الأيزوبروبيل",
    molarMass: 60.1,
    density: 0.786,
    meltingPoint: -89.5,
    boilingPoint: 82.6,
    stateAtRoomTemp: "liquid",
    stateAr: "سائل",
    category: "household",
    hazardLevel: "medium",
    descriptionEn: "Rubbing alcohol (70% or 91%), used as disinfectant and solvent.",
    descriptionAr: "الكحول الطبي (70% أو 91%)، يستخدم كمطهر ومذيب.",
    homeUsesEn: ["Disinfection", "Cleaning electronics", "Solvent", "First aid"],
    homeUsesAr: ["تعقيم", "تنظيف الإلكترونيات", "مذيب", "إسعافات أولية"],
  },
  "MgSO4": {
    formula: "MgSO4",
    commonNameEn: "Epsom Salt (Magnesium Sulfate)",
    commonNameAr: "ملح إبسوم",
    molarMass: 120.37,
    density: 2.66,
    meltingPoint: 1124,
    boilingPoint: 0,
    stateAtRoomTemp: "solid",
    stateAr: "صلب",
    category: "household",
    hazardLevel: "low",
    descriptionEn: "Epsom salt used in baths, gardening, and home remedies.",
    descriptionAr: "ملح إبسوم يستخدم في الحمامات والبستنة والعلاجات المنزلية.",
    homeUsesEn: ["Bath soaks", "Plant fertilizer", "Muscle relaxant", "Crystal growing"],
    homeUsesAr: ["حمامات", "سماد نباتات", "مرخي عضلات", "زراعة بلورات"],
  },
  "C4H6O4Ca": {
    formula: "C4H6O4Ca",
    commonNameEn: "Calcium Acetate",
    commonNameAr: "خلات الكالسيوم",
    molarMass: 158.17,
    density: 1.50,
    meltingPoint: 160,
    boilingPoint: 0,
    stateAtRoomTemp: "solid",
    stateAr: "صلب",
    category: "household",
    hazardLevel: "low",
    descriptionEn: "Can be made at home from eggshells and vinegar. Used in cheese making.",
    descriptionAr: "يمكن تحضيرها في المنزل من قشر البيض والخل. تستخدم في صناعة الجبن.",
    homeUsesEn: ["Cheese making", "Food additive", "Crystal growing"],
    homeUsesAr: ["صناعة الجبن", "إضافة غذائية", "زراعة بلورات"],
  },
};

/** Look up a compound by formula (case-insensitive for common formulas) */
export function getCompoundByFormula(formula: string): Compound | undefined {
  return COMPOUNDS[formula];
}

/** Search compounds by name or formula */
export function searchCompounds(query: string): Compound[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return Object.values(COMPOUNDS).filter(
    (c) =>
      c.formula.toLowerCase().includes(q) ||
      c.commonNameEn.toLowerCase().includes(q) ||
      c.commonNameAr.includes(query.trim())
  );
}

/** Get all household-safe compounds */
export function getHouseholdCompounds(): Compound[] {
  return Object.values(COMPOUNDS).filter((c) => c.category === "household" || c.category === "food");
}
